apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-user
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-admin-user-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: cluster-admin-user
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-user
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-user-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: devops-user
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-user
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-user-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: developer-user
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer-user
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: viewer-user-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: viewer-user
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-user
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: security-user-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: security-user
type: kubernetes.io/service-account-token
